# -*- coding: utf-8 -*-
"""Taller03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_k4L4LAtPz1lIp-aKu-RT1TzckUd2IL
"""

numero_id = int(input("Digite su número de identificación"))
print(numero_id)
nombres = input("Digite sus nombres")
print(nombres)
apellidos = input("Digite sus apellidos")
print(apellidos)
direccion = input("Digite su direccion")
print(direccion)
telefono = int(input("Digite su telefono"))
print(telefono)
edad = int(input("Digite su edad"))
print(edad)
estado_ci = input("Digite su estado civil")
print(estado_ci)
hijos = int(input("¿Cuántos hijos tiene"))
print(hijos)
estatura = int(input("Digite su estatura en cm"))
print(estatura)
fecha = input("Digite su fecha de contratación dd/mm/aaaa")
print(fecha)
sueldo = float(input("¿Cual es su salario?"))
print(sueldo)
dias = int(input("Digite los dias laborados: "))
print(dias)

if edad > 55 :
  nsueldo = sueldo + (sueldo * 0.05)
  print("El sueldo con aumento es ${:,.0f}" .format(nsueldo))
else: 
  if estado_ci == "casado" & hijos > 0 :
    print("Se le otorga un paseo cada Diciembre")
  else: 
     if 1000000 < sueldo < 1500000 :
      nsueldo = sueldo + (sueldo*0.02)
      print(nsueldo)
     else :
      if 1501000 <= sueldo <= 2000000 :
        nsueldo = sueldo + (sueldo * 0.05)
        print(nsueldo)
      else:
        if dias > 20 & suelddo < 1000000 :
          print("Bono de alimentación")
        else :
          print("No tiene beneficio")