# -*- coding: utf-8 -*-
"""Taller01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P9eHK5O42maSBVap9WkrYSRddYQvWl8q
"""

numero_id = input("Digite su número de identificación")
print(numero_id)
nombres = input("Digite sus nombres")
print(nombres)
apellidos = input("Digite sus apellidos")
print(apellidos)
direccion = input("Digite su direccion")
print(direccion)
telefono = input("Digite su telefono")
print(telefono)
edad = input("Digite su edad")
print(edad)
estado_ci = input("Digite su estado civil")
print(estado_ci)
hijos = input("¿Cuántos hijos tiene")
print(hijos)
estatura = input("Digite su estatura en cm")
print(estatura)
fecha = input("Digite su fecha de contratación dd/mm/aaaa")
print(fecha)
sueldo = input("¿Cual es su salario?")
print(sueldo)
dias = input("Digite los dias laborados")
print(dias)